spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/three_kingdoms?serverTimezone=UTC
    username: root
    password: root

web:
  imageUrl: "http://localhost:8080/image/"
