spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/three_kingdoms?serverTimezone=UTC
    username: root
    password: root
    #邮箱验证码配置
    mail:
    # QQ邮箱验证码
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 3473432433@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: vhrgnebyrewvciaj
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    nickname: 三国历史可视化展示平台
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      host: 192.168.56.101
      port: 6379
      database: 0
      timeout: 1800000
      password: root


web:
  imageUrl: "http://localhost:8080/image/"

logging:
  file:
    path: logs
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
