spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/three_kingdoms?serverTimezone=UTC
    username: root
    password: root

web:
  imageUrl: "http://localhost:8080/image/"

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
  file:
    path: logs
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
